version: '3.5'

services:

  elasticsearch:
    container_name: es_1
    build:
      context: elasticsearch/
    #volumes:
    #  - /Users/ben/VSCode/elastic-docker/elasticsearch/config/elasticsearch.yml:./elasticsearch/config/elasticsearch.yml:ro
    #  - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - es_local_dev

  logstash:
    container_name: logstash
    build:
      context: logstash/
    volumes:
      - /Users/ben/VSCode/elastic-docker/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - /Users/ben/Downloads/Engineer2/datasets/blogs.csv:/usr/share/logstash/blogs.csv:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es_local_dev
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - es_local_dev
    depends_on:
      - elasticsearch

networks:
  es_local_dev:
    driver: bridge

volumes:
  esdata1:
    driver: local    