##############################################################################
#  Filebeat configuration to ingest access logs from the blog website.       #
#  The data is already in in JSON format and does not need any processing.   #
#  Extract the blog_access_logs.tar.gz file and set paths correctly          #
##############################################################################

filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

processors:
 - decode_json_fields:
     fields: ['message']
     target: ''
     overwrite_keys: true

 - drop_fields:
     fields: ["message", "prospector", "beat", "source", "offset"]

setup.template.enabled: false

output.elasticsearch:
  hosts: ["es1:9200"]
  #index: "%{[fields.log_type]}-%{[agent.version]}-%{+yyyy.MM.dd}"
  index: "logs_%{[fields.host]}"
  bulk_max_size: 1000
